### ISSUE TITLE
Let SVC remember window size and position

### ISSUE THREAD

**Issue by pstein** [bartekmotyl/simple-video-cutter#10]
SVC should remember its last window size and position on desktop at exit and re-open it with the same pos+size at next startup

Peter

**Comment by bartekmotyl** [comment]
Indeed, at the moment (v0.11) these settings are nit persisted. Beside window pos&size, the following settings are to be persisted as well:
- toolbar locations 
- list/log of processed tasks (?) - with possibility to "reply" the task (or at least load the corrsponding file and set selection accordingly)
- others?

**Comment by bartekmotyl** [comment]
Fixed in release 0.12
