### ISSUE TITLE
Put all icons in 1 toolbars (or in 2 horizontally ROWs) 

### ISSUE THREAD

**Issue by pstein** [bartekmotyl/simple-video-cutter#11]
Currently some menu icons (set start, clear selection,....) are arranged in a vertical toolbar.
I prefer to have such toolbars always horizontally.

Is it possible to add an option to put all icons in 1 toolbar? Or at least in 2 toolbars (at the top) but all horizontally? Maybe as a user option?

Thank you
Peter

**Comment by bartekmotyl** [comment]
Toolbar strips can be rearranged by drag&drop (hint: drag the dotted lines) and put into top or left toolbar container (multiple rows or columns are allowed). The settings are not persisted thought (at least in v0.11) - this will be fixed in issue #10
