### ISSUE TITLE
Add a previous frame command

### ISSUE THREAD

**Issue by piggylux** [bartekmotyl/simple-video-cutter#15]
As for the `Next frame` button, it would be very useful to have a `Previous frame` one

**Comment by bartekmotyl** [comment]
Unfortunately, this is not that easy, as the underlying library (wrapper for VLC library) does not support navigation to previous frame, only to next frame. I would need to check whether it is possible to get over this limitation somehow.

**Comment by bartekmotyl** [comment]
Implemented, will be released in version 0.29.0. 

The solution is not perfect and jumps 2-3 frames backward, but I think it better than nothing.
