### ISSUE TITLE
Drag and Drop not working (sometimes)

### ISSUE THREAD

**Issue by Runnin-N-Gunnin** [bartekmotyl/simple-video-cutter#16]
Hello

I've encountered an issue where drag and drop is not working correctly. It's a coin toss whether or not it's going to work. I have to keep restarting the application until it works.

I'd like to drag and drop single files from Explorer rather than manually opening a file in the application.

What I've tried: First Building the project in Visual Studio and then I ran prepare-dist.cmd (build.ps1) file, re-installing FFMpeg, tried x86 and x64 etc

I run a customized version of Windows 10 Pro 64.

Thanks for any suggestions. Great software.

**Comment by bartekmotyl** [comment]
Hmm, that's sounds interesting, thank you for reporting. 
Can you describe what you mean by "drag and drop is not working" ?
Do you see mouse pointer changing when you move mouse over the simple-video-cutter window? Do you maybe see the "no entry" icon?
What happens when you drop the file? What kind of file you are dragging? Does the problem occur for any type of file (mov, mp3, avi..)? Do you drag one file only? (SVC supports drag& drop of one file only).

**Comment by Runnin-N-Gunnin** [comment]
Hello again bartekmotyl. I'm sorry for the late reply.

> Do you maybe see the "no entry" icon?

Yes exactly! And that's what I mean by "drag and drop is not working".

> What happens when you drop the file?

Nothing.

> What kind of file you are dragging?

Mostly .mp4-files and sometimes .avi-files

> Does the problem occur for any type of file (mov, mp3, avi..)?

I believe so, yes. I'll update you on this whenever I have the time to test it again. Happens on .mp4 and .avi atleast.

> Do you drag one file only?

Yes.

-----------------------------------------------------------------

To make it even more complicated (maybe): when a file has been drag and dropped & cut, it'll show the no-entry icon all of a sudden when trying to drop a new file. This rarely happens but it has happened atleast 2 times. A restart is the only fix.

Thanks!

**Comment by Runnin-N-Gunnin** [comment]
Back again with a small update -- after doing a bunch of testing with various filetypes in various situations. it is a strange bug happening somewhere

The type of the file dropped is not important in this situation. Either it just works **or** it'll show the no-entry icon for the remainder of execution-time.
Even rarely; it'll crap-out mid-cuttin'-sesh - I mean the whole drag&drop-functionality will just take it's hat n leave out the door - _goodbye!_ - meanwhile I'm sat here cursing again hella confused

Once "targeted" by the aforementioned 'drag&drop-bug' there is no way to cure it other than doing a restart of the application and hope for the best.

est failure-rate on execution is ~50%. No way to predict, no obvious patterns to observe. Can work several times in a row and vice versa.

est failure chance after drag and drop has worked _atleast_  for 1 operation: ~1 in 50 days of usage. Ex: If I were to use the application everyday for 50 days I'd expect it to occur atleast 1 time in 1 day of those 50. 

When it works though - it's working great; hundreds of d&d-operations performed in a row; no sweat no restart all smiles.
I'm out of time & ideas for now. will answer questions and/or test suggestions.

maybe someone can reply here and confirm if they have experienced the same thing?

**Comment by bartekmotyl** [comment]
Closing as no response and lack of replication procedure.
