### ISSUE TITLE
Add .mkv as an "Extensions of video files" by default

### ISSUE THREAD

**Issue by ghost** [bartekmotyl/simple-video-cutter#21]
Maybe there is a good reason it isn't there by default, but it seems like it should be there since it's a very common file extension.

**Comment by bartekmotyl** [comment]
This indeed sounds reasonable. I have no idea why it was not included. 
Will be included in next release, but until then you can manually edit your config.json file (while program is not running) and add this extension to the list of supported video files.

**Comment by bartekmotyl** [comment]
Fixed in development. Will be included in release 0.16
