### ISSUE TITLE
Error at launch (unhandled exception)

### ISSUE THREAD

**Issue by andiandi13** [bartekmotyl/simple-video-cutter#23]
I'm using Windows 7 x86, and when I open simple video cutter I have this message 

![SimpleVideocuter Error](https://user-images.githubusercontent.com/19387072/92411341-b9c6b180-f147-11ea-8671-b4c753e940ee.png)

Where does it come from and how to solve that

Thank you.

**Comment by bartekmotyl** [comment]
Could you please attach information about .net frameworks installed on your machine? Preferably output from a netver tool 
http://www.asoft.be/prod_netver.html

**Comment by andiandi13** [comment]
@bartekmotyl Here is the report from netver tool :

<32Bit>
2.0.50727.5420
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

==== Installed .NET Frameworks ====
.NET FW 2.0 SP 2 (CLR 2.0)
.NET FW 3.0 SP 2 (CLR 2.0)
.NET FW 3.5 SP 1 (CLR 2.0)
.NET FW 4.6.1 (CLR 4.0)

==== Installed .NET Core Runtime 64bit ====
32bit OS cannot install 64bit Runtimes

==== Installed .NET Core Runtime 32bit ====
No .NET Core x86 Runtime

==== Installed .NET Core Sdk 64bit ====
32bit OS cannot install 64bit Sdk's

==== Installed .NET Core Sdk 32bit ====
No .NET Core x86 Sdk

==== Languages ====
< Installed Languages 3.0>
English - United States
< Installed Languages 3.5.x>
English - United States
< Installed Languages 4.x>
English - United States

==== Updates ====
==== END REPORT ====

**Comment by bartekmotyl** [comment]
Please try to install .Net Framework 4.7.2 (32 bit version) that can be downloaded e.g. here https://support.microsoft.com/en-us/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows

**Comment by andiandi13** [comment]
I got this error while installing Net Framework 4.7.2 

"Final Result: Installation failed with error code: (0x800B0109), "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. "

Same with further versions...

**Comment by bartekmotyl** [comment]
Hmm, this is weird you cannot install official .Net framework. Can you try to install it via web installer: https://dotnet.microsoft.com/download/dotnet-framework/net472 ?

**Comment by bartekmotyl** [comment]
Closing as no further response (and no other reports)
