### ISSUE TITLE
webm support?

### ISSUE THREAD

**Issue by psociety** [bartekmotyl/simple-video-cutter#24]
Will SimpleVideoCutter support webm in a near future?

**Comment by bartekmotyl** [comment]
In fact it is already supported, the extension is just missing on the list of supported video files. 
I will add it in next release. In meantime you can edit your config.js file add missing entry, e.g. like this: 
`  "VideoFilesExtensions": [
    ".mov",
    ".avi",
    ".mp4",
    ".wmv",
    ".rm",
    ".mpg",
    ".mkv",
    ".webm",
  ]`
But please remember to edit the file when program is not running, otherwise it will be overwritten when program closes.

**Comment by psociety** [comment]
Sorry to reopen but webm doesn't seem to be fully supported only with the videoFilesExtensions hack:
![1](https://user-images.githubusercontent.com/29523682/98408285-348d4980-2071-11eb-8fb4-1c14031400af.png)

With an mp4:
![1](https://user-images.githubusercontent.com/29523682/98408345-4ff85480-2071-11eb-9011-c827c20c419a.png)

With webm, video and thumbnails also look "broken" when manually jumping from one point to another:
![1](https://user-images.githubusercontent.com/29523682/98408513-8afa8800-2071-11eb-87a6-5615b439d529.png)

mp4 is fine:
![1](https://user-images.githubusercontent.com/29523682/98408606-ba10f980-2071-11eb-8c48-ab03b386cdb9.png)

**Comment by bartekmotyl** [comment]
The "hack" should have no influence on the behavior. This seems to be a problem with this particular file (or files of similar characteristics). I have tested [sample webm file](https://www.webmfiles.org/demo-files/) and it works fine. 
If the sample file also works for you, then it means there is something wrong with the other file. Can you share it (link) ?
Might be also a good idea to check whether the file is properly played with VLC (Simple Video Cutter uses VLC libs under the hood). 

And btw. I have just released version 0.17 of Simple video Cutter which has built-in support for webm files.

**Comment by psociety** [comment]
Sure, everything that i record with this extension:
https://chrome.google.com/webstore/detail/screen-recorder/hniebljpgcogalllopnjokppmgbhaden?hl=en

Sample: https://gofile.io/d/pGKv9L

**Comment by bartekmotyl** [comment]
Thanks, I am able now to replicate the issue on my machine!

**Comment by bartekmotyl** [comment]
Sadly, this seems to be limitation of VLC itself (or incorrect use of webm format by screen recorder). 
As written e.g. [https://superuser.com/questions/1585091/fixing-the-length-duration-of-a-webm-file-takes-too-much-time-by-ffmpeg](https://superuser.com/questions/1585091/fixing-the-length-duration-of-a-webm-file-takes-too-much-time-by-ffmpeg) the H.264 is not supported by VLC in webm files. 
As you can see on the picture below, VLC player did not recognize length of this file either: 
![obraz](https://user-images.githubusercontent.com/29923773/101283701-5dbe0880-37dc-11eb-8aa1-3dd5546a3dce.png)

Unfortunately I am not able to fix it in SVC, this is a problem in LibVLC. I have created a separate issue though (#28) to add a warning for the user in this case.
