### ISSUE TITLE
add variable for filename {startframe} or {starttime}

### ISSUE THREAD

**Issue by ingof** [bartekmotyl/simple-video-cutter#25]
can you please add starttime variable for filenames? (00:00:00,000)
For example {starttime} or {startframe}?

With startframe i can calculate the starttime by myself
I cut several video files with existing subtitle-file (SRT)
so i can also cut the exported range of my SRT-file and add to the cutted video directory

**Comment by bartekmotyl** [comment]
Implemented, will be included next release (0.17)
I have added: 

- `SelectionStart` / `SelectionEnd` (hhmmss)
- `SelectionStartMs` / `SelectionEndMs` (same as above, but in milliseconds)
- `Duration` (hhmmss)
