### ISSUE TITLE
ffmpeg.zeranoe.com has closed

### ISSUE THREAD

**Issue by ghost** [bartekmotyl/simple-video-cutter#26]
https://www.reddit.com/r/ffmpeg/comments/ikht2k/ffmpegzeranoecom_will_close_on_sep_18_2020/

**Comment by bartekmotyl** [comment]
Uh, thanks for info, I have missed the announcement.
Will have to link to another source.

**Comment by ghost** [comment]
Would one of the download links [provided on the official website](https://ffmpeg.org/download.html#build-windows) work?

**Comment by bartekmotyl** [comment]
Yes, but as they pretty fresh so far (started after zeranoe has closed) I am not sure which one would be better.

**Comment by bartekmotyl** [comment]
Switched to https://www.gyan.dev/ffmpeg/builds/ in version 0.17
