### ISSUE TITLE
Requests: lossless and frame exact?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [bartekmotyl/simple-video-cutter#31]
hi.
Does it allow frame exactly video navigation and cut?
Will it save loss  less without re-encode?
thx :)

**Comment by bartekmotyl** [comment]
Yes, SVC  allows loss less cutting (by default) but allows to re-encode as well, if needed (e.g. change format). 
Supports 'next frame' navigation (no 'previous frame' though) but it depends on the codec as well (e.g. for mp4 it is possible to position the cut only at certain places)
