### ISSUE TITLE
dead FFmpeg link?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [bartekmotyl/simple-video-cutter#32]
Dead Link on your start page?
FFmpeg release page : https://ffmpeg.zeranoe.com/builds/

**Comment by bartekmotyl** [comment]
Since #26 / version 0.17.0 the link has been changed to https://www.gyan.dev/ffmpeg/builds/

**Comment by Clemens-Ratte-Polle** [comment]
yes, but please correct that also on your page :)
https://github.com/bartekmotyl/simple-video-cutter
it
