### ISSUE TITLE
Feature Request: Storage path for SimpleVideoCutter_config.json (for example romaing profiles)

### ISSUE THREAD

**Issue by JK-FFM** [bartekmotyl/simple-video-cutter#39]
Hi,

in our school IT environment we work with profiles, so the option to specify a path in which the configuration file will be stored is essential. Our users do not have elevated permissions on the PCs, but we should provide the program as a portable APP under C: \ Program Files.

Ideally, the storage location can be defined using a redistributable option so that the SimpleVideoCutter_config.json is stored on a path with write permissions for the user.

**Comment by bartekmotyl** [comment]
Hi, 
indeed, this is something that should be added, but unfortunately I cannot tell when. 
Currently the `config.json` file is always read/written in the same directory when executable file is located, so one of possible workarounds is to install program to a directory which is writable for current user  e.g. `c:\Users\<username>\Documents\SimpleVideoCutter`

**Comment by JK-FFM** [comment]
Hi bartekmotyl,

thanks for the feedback. The installation option under c: \ Users \ <username> \ Documents \ SimpleVideoCutter is unfortunately not an option, we had already checked this. Thus, 167 MB per user would be stored on our servers. This also has an impact on the backup, etc.! So let's just wait and see and hope for a solution in the future. Basically, the software is great and our schools would like to use it.

**Comment by Psych05** [comment]
Hi there, it is indeed very common in larger, especially corporate environments that users cannot have write permissions where executables are stored.

The main problem I see is that currently, Simple Video Cutter always tries to open config.json for writing, and crashes when permissions are missing. That is generally no good behaviour.

I believe the problem should at the very least be gracefully dealt with. For example, settings in an existing config.json could be respected (read-only) in that situation, but the application would continue to function normally. Settings could not be changed by the user then, but that that might even be desirable in such environments!

**Comment by bartekmotyl** [comment]
Implemented in release 0.19. 

Starting from this release, default location of configuration file is user's local AppData folder (usually `C:\Users\<username>\AppData\Local\SimpleVideoCutter`) which is expected always be writable. Feel free to copy over your previous configuration file if necessary. 

Additionally, there are three new command line options available that control placement of the configuration file: 

- `--configCurrentFolder` - in the same folder where exe file is located (old behavior)
- `--configLocalApplicationData` - in the AppData\Local folder  (this is now the default) 
- `--configApplicationData` - in the AppData\Roaming folder (this means the file is copied when user logs in on another machine in domain environment). Please note this option may be useful only if ffmpeg path points to a shared resource as well (e.g. network drive) or it is expected ffmpeg is always installed in the same place on all machines.
