### ISSUE TITLE
configurable size of preview area popup

### ISSUE THREAD

**Issue by the-liquid-metal** [bartekmotyl/simple-video-cutter#43]
in 1920x1080 screen, the popup preview area is too large and annoying while the movie is played. it would be better if this popup is configurable, so people can adjust its dimension.

**Comment by bartekmotyl** [comment]
Can you maybe share (if possible) a screenshot from your screen? I think this i not only about resolution, but also about dpi etc.

**Comment by the-liquid-metal** [comment]
![image](https://user-images.githubusercontent.com/238188/144137570-6b7fa746-b247-40f7-a01b-13199022525e.png)

**Comment by the-liquid-metal** [comment]
Additional points worth including: add an option to completely hide the popup.

**Comment by bartekmotyl** [comment]
Starting from release 0.20 it is possible to use `ShowPreview` parameter (in `config.json`) to control whether preview should be shown at all (`true` -> shown, `false` -> hidden).

**Comment by bartekmotyl** [comment]
Implemented in version 0.21
