### ISSUE TITLE
Improved display of timeline tick labels

### ISSUE THREAD

**Issue by the-liquid-metal** [bartekmotyl/simple-video-cutter#44]
As the title says.

**Comment by bartekmotyl** [comment]
Well, this is in fact a "feature". Depending on zoom level, distance between ticks becomes smaller or larger. There is a mechanism that prevents from drawing tick labels when there is not enough space. 
For videos shorter than 1 hour, ticks are labeled `mm:ss`, so take relatively small amount of space. But for longer videos, tick labels are formatted as `hh:mm:ss` what means more space is required to place them and in most cases they are invisible. 
This is maybe not a perfect mechanism, just a pragmatic solution that may be improved in the future. 

Hint: one can change zoom level using control key and mouse wheel. This way one may cause even longer labels to show (but of course scrolling becomes an issue then).

**Comment by the-liquid-metal** [comment]
> Well, this is in fact a "feature". Depending on zoom level, distance between ticks becomes smaller or larger. There is a mechanism that prevents from drawing tick labels when there is not enough space. For videos shorter than 1 hour, ticks are labeled `mm:ss`, so take relatively small amount of space. But for longer videos, tick labels are formatted as `hh:mm:ss` what means more space is required to place them and in most cases they are invisible. This is maybe not a perfect mechanism, just a pragmatic solution that may be improved in the future.
> 
displaying every 2 or 3 ticks potentially solve the problem and making it consistent before and after 1 hour.

> Hint: one can change zoom level using control key and mouse wheel. This way one may cause even longer labels to show (but of course scrolling becomes an issue then).

increasing/decreasing tick's width is very slowly. scrolling 3 or 4 times to become 2x of original width is common in other app.

**Comment by bartekmotyl** [comment]
> displaying every 2 or 3 ticks potentially solve the problem and making it consistent before and after 1 hour.

This indeed sound like very good idea 👍

**Comment by bartekmotyl** [comment]
Implemented in version 0.20
