### ISSUE TITLE
cut selection area is gone after perform cut

### ISSUE THREAD

**Issue by the-liquid-metal** [bartekmotyl/simple-video-cutter#45]
Sometimes we have to evaluate the output with real movie player. There is no way to edit the selection area after perform cut: the selection area is gone. we have to repeat the step from the beginning.

**Comment by bartekmotyl** [comment]
Starting from release 0.20 it is possible to control whether to clear selection after cut. There is a new setting in `config.json` - `KeepSelectionAfterCut`. `true`: do not clear selection after cut, `false` (default): clear selection after cut.

**Comment by the-liquid-metal** [comment]
It shold be `KeepSelectionAfterCut`: `true` by default.
