### ISSUE TITLE
distinguishable tickbar

### ISSUE THREAD

**Issue by the-liquid-metal** [bartekmotyl/simple-video-cutter#48]
On lengthy movies, it is hard to point an exact brief position, before subsequent click on zoom auto button.

Some apps use different style on tickbar to mark every 1 hour, or 1/2 hour, or 1/4 hour. There are combinations in use: color, length, and width. The simplest form uses different color for regular ticks and common time fractions as above. More stylist app uses 3 different color to distinguish: regular, 1/4, and 1 hour. It also can be applied to tick length and width.

A note on tick length: regular tick can be a form of dot, not bar, so it does not consume too much space.

It is also make sense to combine the three to achieve distinguishable tickbar.

**Comment by bartekmotyl** [comment]
Timeline has been reworked in version 0.20. It should be much more readable now. Includes also indication of key frames (as alternate light/dark rectangles).
