### ISSUE TITLE
request to trim video without re-encoding

### ISSUE THREAD

**Issue by hjgyuhuk** [bartekmotyl/simple-video-cutter#5]
Hi,
I noticed the video was re-encoded when using this tool,
Can you support ffmpeg option `-vcodec copy -acodec copy` to avoid this.

**Comment by bartekmotyl** [comment]
Yeah, my todo list includes an extension to allow defining ffmpeg "profiles" (set of ffmpeg parameters) that will be used when adding task to the queue. This would include re-encoding to other formats, scaling etc.

**Comment by hjgyuhuk** [comment]
That's helpful,I hope it can be default furtherly.
Thanks for your great work.

**Comment by bartekmotyl** [comment]
I reopen the issue to represent enhancement to be implemented.

**Comment by bartekmotyl** [comment]
Implemented in release 0.11.0 - by default we use "-codec copy" when calling ffmpeg (this can be changed in config file thought).
