### ISSUE TITLE
Simple video cutter is not visible, location saved to relative extremes in JSON?

### ISSUE THREAD

**Issue by Aida-Enna** [bartekmotyl/simple-video-cutter#56]
I have to swap monitors around a lot for work (switching HDMI inputs which causes them all to move all over the place) and today I couldn't see the program at all. After some confusion, I figured it was set to a location outside of the viewable area, and I was correct. I opened the JSON and had this line:
`  "MainWindowLocation": "-32000, -32000, 160, 28",`

Once I reset the -32000 values both to 1, it showed up properly (albeit small) on my primary monitor.

**Comment by bartekmotyl** [comment]
Thanks for reporting

**Comment by bartekmotyl** [comment]
Fixed in development branch, fix will be included in next release
