### ISSUE TITLE
Possibility to customize visibility of timeline tooltip

### ISSUE THREAD

**Issue by Uzukii** [bartekmotyl/simple-video-cutter#57]
They just get in the way and I'd rather be able to see/read what's under them.

**Comment by bartekmotyl** [comment]
I am not exactly sure which  UI element you mean. 
If you refer to preview (single frame of the video at currently hovered position) then in version 0.21 I implemented possibility to change size of the preview or even to disable it (see #43). 

Regarding the tooltip (on timeline): first of all, it is currently not shown correctly - see bug #58. 
But in general, I agree it should be possible to customize whether to show it or not.

**Comment by bartekmotyl** [comment]
Fixed together with #58
