### ISSUE TITLE
Add "Jump to prev/next keyframe"

### ISSUE THREAD

**Issue by pstein** [bartekmotyl/simple-video-cutter#7]
I prefer to cut videos always at keyframe positions.

As far as I can see there is no necessary "jump to prev/next keyframe" menu in SVC.

Could you add it?

Thank you
Peter

**Comment by bartekmotyl** [comment]
There is a key shortcut '.' (dot) that navigates to next frame. As far as I can see, VLC (the underlying engine I use to render the video) does not provide option to navigate to "previous frame", unfortunately. 
Anyway, exposing the "next frame" button in UI is a good idea.

**Comment by bartekmotyl** [comment]
Implemented in release 0.11.0 - toolbar button has been added.
