### ISSUE TITLE
[Feature Request] allow relative path to ffmpeg

### ISSUE THREAD

**Issue by wwwurst** [bartekmotyl/simple-video-cutter#72]
e.g. ".\ffmpeg\bin\ffmpeg.exe" for portable use
Or, even easier, also check for ffmpeg.exe in same directory as SimpleVideoCutter.exe if no path to ffmpeg is given.

I just checked, relative path is possible to manually edit into config.json , would be nice if it worked without this hack.

**Comment by bartekmotyl** [comment]
Implemented, will be included in release 0.26: 

- by default, ffmpeg path is set to `.\ffmpeg.exe` so SVC looks for `ffmpeg.exe` (and `ffprobe.exe` !) in the same directory where main program is located
- it is possible to use relative paths in the settings window
