### ISSUE TITLE
Define "same as input dir" for output directory

### ISSUE THREAD

**Issue by pstein** [bartekmotyl/simple-video-cutter#8]
I would like to define the input directory of the video always as output directory of cut work.

Currently users have to define a static directory.

Could you allow the definition of "same as input dir"?

Thank you
Peter

**Comment by bartekmotyl** [comment]
Sounds good, I will try to include this in next release.

**Comment by bartekmotyl** [comment]
Implemented in release 0.11.0 - {SameFolder}

**Comment by bartekmotyl** [comment]
Reopen, as something went wrong in release 0.11 and {SameFolder} doesn't work correctly :(

**Comment by bartekmotyl** [comment]
Fixed in development, will be included in release v0.12

**Comment by GravuTrad** [comment]
Seems bugged with windows 7 (not mine, but few users freeze). Working well with windows 10 (my computer).

**Comment by bartekmotyl** [comment]
Can you precise what does it mean 'freeze'? Unfortunately I do not have access to any Windows 7 to check myself.  Maybe you can provide a screenshot or screen recording?
