### ISSUE TITLE
.net update?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [bartekmotyl/simple-video-cutter#87]
SVC 0.28 does not run and wants to download the Framework Microsoft NetCore.app.
![2023-12-05_191944 Screenshot](https://github.com/bartekmotyl/simple-video-cutter/assets/10136291/7ced2209-68c8-4f3d-98a8-515a5177b3e2)

Whats this?
I didn't have such question since i can remember...

It downloads 54 MB :
windowsdesktop-runtime-7.0.14-win-x64.exe

With Windows Features i found out that i use .NET Framework 3.5 

Shall we download .NET Framework 4.8.1 ?
https://dotnet.microsoft.com/en-us/download/dotnet-framework

Shouldnt we download .NET 8.0 ?
https://dotnet.microsoft.com/en-us/download

**Comment by bartekmotyl** [comment]
Hi, 
since v0.26 Simple Video Cutter requires .net 7. Please see details [here](https://github.com/bartekmotyl/simple-video-cutter/releases/tag/v0.26.0)

**Comment by bartekmotyl** [comment]
Simple Video Cutter is written in C# and runs on .NET framework. 
Before version 0.26 it was built on top of .NET Framework version 4.7 which is included is most version of Windows, even the old ones. 
From version 0.26 onwards, SVC is built on .NET Framework version 7. In newer versions of Windows this version of .NET Framework is also pre-installed and one does not need to download anything. If it is missing on your version of Windows, you need to download & install it separately from this page: https://dotnet.microsoft.com/en-us/download/dotnet/7.0
downloading the ".NET Desktop Runtime 7.0.14"
