### ISSUE TITLE
Stop deleting the selection after cutting

### ISSUE THREAD

**Issue by PinkSerenity** [bartekmotyl/simple-video-cutter#88]
I find it very invasive that the software decides that I no longer need the selection and simply deletes it. What if I accidentally pressed the Cutting button or forgot to press`Shift? In these cases I have to select everything again.
I think it should be optional whether the selection is deleted. I additionally think that it should be opt-in, since I don't think such invasive behavior should be the default, but opt-out works just as well.

**Comment by 0lm** [comment]
This actually happened to me a few times: I forgot to press Shift and had to look for the perfect frames/timings again.

**Comment by bartekmotyl** [comment]
Fixed, will be included in next release. The `KeepSelectionAfterCut` setting now defaults to `true`.  Existing users, that want to keep old config file, may manually change the `KeepSelectionAfterCut` to `true` in the `config.json`.

**Comment by PinkSerenity** [comment]
I'm seriously sorry. I never checked the config file before. I was looking for one in the same directory, but after that I just accepted that there isn't one. I should have looked in the readme first. I agree that it should be the default behavior, but I wouldn't have opened the issue if I had noticed it. So again, sorry for that, next time I will definitely check better.

**Comment by bartekmotyl** [comment]
No worries. I also forgot that I added this undocumented option some time ago... 😄
